# fly.toml app configuration file generated for x-bookmarks-bot on 2026-02-22T15:49:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'x-bookmarks-bot'
primary_region = 'lax'

[build]

[[mounts]]
  source = 'data'
  destination = '/app/data'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
